### ISSUE TITLE
Sake crashes when .shastore is deleted without `sake clean`

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#48]
Example in `functests/test2` with an empty .shastore:

```
The following fields were not recognized and will be ignored
  - achtung
Traceback (most recent call last):
  File "../../sake", line 211, in <module>
    args.force, args.recon, args.parallel)
  File "/media/ryan/stuff/sake5/sakelib/build.py", line 482, in build_this_graph
    check_shastore_version(from_store, verbose)
  File "/media/ryan/stuff/sake5/sakelib/build.py", line 72, in check_shastore_version
    if 'sake version' not in from_store:
TypeError: argument of type 'NoneType' is not iterable
```

With this simple Sakefile:

```yaml
all:
    - build stuff

build stuff:
    help: ack
    formula: cp x.in x.out
    output:
        - x.out
    dependencies:
        - x.in
```

deleting .shastore manually and then running Sake yields this:

```
Running target build stuff
cp x.in x.out
Traceback (most recent call last):
  File "../sake", line 228, in <module>
    args.force, args.recon, args.parallel)
  File "/media/ryan/stuff/sake5/sakelib/build.py", line 536, in build_this_graph
    in_mem_shas['files'][output] = {"sha": get_sha(output)}
KeyError: u'files'
```

Running it again shows no error.

**Comment by tonyfischetti** [comment]
I can't replicate this. What version of sake are you using. Try to replicate this in the newest version.
