### ISSUE TITLE
Error when using bad .shastore

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#66]
An older version of Sake had generated the following `.shastore`:

```yaml
---
...
```

Running Sake resulted in this:

```
Traceback (most recent call last):
  File "/usr/local/bin/sake", line 5, in <module>
    pkg_resources.run_script('master-sake==0.9.6', 'sake')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 528, in run_script
    dist.insert_on(self.entries, entry)
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1401, in run_script
    raise IOError('"os.rename" and "os.unlink" are not supported '
  File "/usr/local/lib/python2.7/dist-packages/master_sake-0.9.6-py2.7.egg/EGG-INFO/scripts/sake", line 204, in <module>
    
  File "build/bdist.linux-x86_64/egg/sakelib/build.py", line 494, in build_this_graph
  File "build/bdist.linux-x86_64/egg/sakelib/build.py", line 70, in check_shastore_version
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tonyfischetti** [comment]
Awesome, thanks!
